

# Database H2
spring.datasource.url=jdbc:h2:file:./data/cotipdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

#
spring.threads.virtual.enabled=true

# General bank paths
cotip.continental.bank.bearer.path=https://apibanking-gw.bancontinental.com.py/autenticarServicio/v1/realms/interno
cotip.continental.bank.bearer.apikey=3c35bb9e5fa948adb8d64c123d9d1a45
cotip.continental.bank.bearer.client=006f7995-3d33-4afe-8c56-e3b47377092c
cotip.continental.bank.bearer.client-id=webinstitucional
cotip.continental.bank.bearer.grant-Type=client_credentials
cotip.continental.bank.bearer.scope=profile

cotip.continental.bank.path=https://apibanking-gw.bancontinental.com.py/divisas/v1/api/monedas/cotizaciones
cotip.continental.bank.apikey=3c35bb9e5fa948adb8d64c123d9d1a45
cotip.familiar.bank.path=https://www.familiar.com.py/
cotip.gnb.bank.path=https://www.bancognb.com.py/public/currency_quotations
cotip.rio.bank.path=https://www.rio.com.py/endpoint/cotizaciones
cotip.solar.bank.path=https://www.solar.com.py/
cotip.bnf.bank.path=https://www.bnf.gov.py/tarifario-2024-
cotip.atlas.bank.path=https://www.bancoatlas.com.py/web
cotip.fic.financial.path=https://fic.com.py/
cotip.maxicambios.path=https://www.maxicambios.com.py/

logging.level.org.springframework.boot.context.properties=DEBUG
