spring.application.name=Cotip

#db - h2
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# port
server.port=8081

# General bank paths
cotip.continental.bank.bearer.path=https://apibanking-gw.bancontinental.com.py/autenticarServicio/v1/realms/interno
cotip.continental.bank.path=https://apibanking-gw.bancontinental.com.py/divisas/v1/api/monedas/cotizaciones
cotip.familiar.bank.path=https://www.familiar.com.py/
cotip.gnb.bank.path=https://www.bancognb.com.py/public/currency_quotations
cotip.rio.bank.path=https://www.rio.com.py/endpoint/cotizaciones
cotip.solar.bank.path=https://www.solar.com.py/
cotip.bnf.bank.path=https://www.bnf.gov.py/tarifario-2024-
cotip.atlas.bank.path=https://www.bancoatlas.com.py/web
cotip.fic.financial.path=https://fic.com.py/
cotip.maxicambios.path=https://www.maxicambios.com.py/

logging.level.org.springframework.boot.context.properties=DEBUG

# Banco Continental details
spring.config.import=classpath:cotipdetails.properties