# Banco Continental
cotip.providers.CONTINENTAL_BANK.phone-number=123456789
cotip.providers.CONTINENTAL_BANK.email=continental@example.com
cotip.providers.CONTINENTAL_BANK.location.address=123 Main St
cotip.providers.CONTINENTAL_BANK.location.latitude=-25.2637
cotip.providers.CONTINENTAL_BANK.location.longitude=-57.5759
cotip.providers.CONTINENTAL_BANK.website=https://continental.com
cotip.providers.CONTINENTAL_BANK.whatsapp-link=https://wa.me/123456789
cotip.providers.CONTINENTAL_BANK.schedule.daily-schedules[0].day=lunes
cotip.providers.CONTINENTAL_BANK.schedule.daily-schedules[0].opening-time=08:00
cotip.providers.CONTINENTAL_BANK.schedule.daily-schedules[0].closing-time=21:00

# Banco Familiar
cotip.providers.FAMILIAR_BANK.phone-number=987654321
cotip.providers.FAMILIAR_BANK.email=familiar@example.com
cotip.providers.FAMILIAR_BANK.location.address=456 Another St
cotip.providers.FAMILIAR_BANK.location.latitude=-26.2637
cotip.providers.FAMILIAR_BANK.location.longitude=-58.5759
cotip.providers.FAMILIAR_BANK.website=https://familiar.com
cotip.providers.FAMILIAR_BANK.whatsapp-link=https://wa.me/987654321
cotip.providers.FAMILIAR_BANK.schedule.daily-schedules[0].day=martes
cotip.providers.FAMILIAR_BANK.schedule.daily-schedules[0].opening-time=09:00
cotip.providers.FAMILIAR_BANK.schedule.daily-schedules[0].closing-time=20:00
