# Archivo base para ejecutar migraciones de Cotip

changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
driver=org.postgresql.Driver

# Objetivo de base de datos
host=localhost
port=5432
database=cotip
schema=public

# Credenciales
username=postgres
password=123456

# Configuracion efectiva de Liquibase
url=jdbc:postgresql://localhost:5432/cotip
defaultSchemaName=public
liquibaseSchemaName=public
